### ISSUE TITLE
Random welcome questions

### ISSUE THREAD

**Issue by KeatonSK** [networking-discord/network-ranger#4]
Have a new pool of questions for new members chosen at random.

**Comment by KeatonSK** [comment]
Currently working on this and have MongoDB working on private version, will push and merge when ready.

**Comment by KeatonSK** [comment]
Most of my code is ready, I'm waiting for @jrokeach's code to add into mine to the push.

**Comment by jrokeach** [comment]
Feel free to submit a pull and we can just merge it in when ready.

[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "
https://github.com/networking-discord/network-ranger/issues/4#issuecomment-597957465
",
"url": "
https://github.com/networking-discord/network-ranger/issues/4#issuecomment-597957465
",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jrokeach** [comment]
Superceded by nrweb.
