### ISSUE TITLE
Welcome Questions Needed

### ISSUE THREAD

**Issue by jrokeach** [networking-discord/network-ranger#42]
We need a new question for the entry because you can copy and paste the question (What is the prefix length of 123.45.67.89 with a netmask of 255.255.255.240?) directly into Google and get the answer.
Anything else that would be an appropriate day 0 networking question we could use? Please comment here.

**Comment by rahul-sundaresan** [comment]
One of the IP address of googles DNS servers is 8.8.8.8. In a network, a router's LAN facing interface has the IP address 192.168.1.1. One of the hosts in the network has the IP address 192.168.1.25
Which IP address would you configure as the hosts default gateway so that traffic from the host can reach googles servers 
1. 8.8.8.8
2. 192.168.1.1
3. 192.168.1.25
4. 255.255.255.255

You can change the question as to see fit

**Comment by rahul-sundaresan** [comment]
How many /64s are available in the network 2001:db8:ff00:1000::/60

**Comment by jrokeach** [comment]
> One of the IP address of googles DNS servers is 8.8.8.8. In a network, a router's LAN facing interface has the IP address 192.168.1.1. One of the hosts in the network has the IP address 192.168.1.25
> Which IP address would you configure as the hosts default gateway so that traffic from the host can reach googles servers 
> 1. 8.8.8.8
> 2. 192.168.1.1
> 3. 192.168.1.25
> 4. 255.255.255.255
> 
> You can change the question as to see fit 

I love the scenario based question. Might tweak it a bit but I think that could fit nicely in a question pool. The only thing I think we'll need to work significantly with this one is that the fact that users have unlimited retries is fundamentally incompatible with multiple choice. Maybe once we have a more established pool of questions we could do multiple choice and give the user a new question when they get one wrong.

**Comment by rahul-sundaresan** [comment]
Alice wants to send a message to Bob (that he can understand) over a channel that Charlie is spying on. What can Alice do to send the message without Charlie deciphering what she sent?
1. Encrypt the message with Bob's public key
2. Encrypt the message with Alice's public key
3. Hash the message with the SHA-1 Algorithm

**Comment by rahul-sundaresan** [comment]
Acme Inc has developed an application which has to send data which absolutely cannot be lost by the receiver even when the data is sent over a lossy link. What transport layer protocol should Acme Inc use?

1. TCP
2. UDP 
3. DHCP
4. ID10T

**Comment by rahul-sundaresan** [comment]
> > One of the IP address of googles DNS servers is 8.8.8.8. In a network, a router's LAN facing interface has the IP address 192.168.1.1. One of the hosts in the network has the IP address 192.168.1.25
> > Which IP address would you configure as the hosts default gateway so that traffic from the host can reach googles servers
> > 
> > 1. 8.8.8.8
> > 2. 192.168.1.1
> > 3. 192.168.1.25
> > 4. 255.255.255.255
> > 
> > You can change the question as to see fit
> 
> I love the scenario based question. Might tweak it a bit but I think that could fit nicely in a question pool. The only thing I think we'll need to work significantly with this one is that the fact that users have unlimited retries is fundamentally incompatible with multiple choice. Maybe once we have a more established pool of questions we could do multiple choice and give the user a new question when they get one wrong.

How many questions are you looking for? 😀

**Comment by rahul-sundaresan** [comment]
What device will you use to connect 3 separate networks with different network IDs 
1. Network combinator 
2. Crossover fiber pair transceiver
3. Multi mode IP capable infieggband 
4. Router
5. Active directory system

**Comment by 1Ludwig** [comment]
Which layer does IP belong to in the OSI model?
1. Layer 1
2. Layer 2
3. Layer 3
4. Layer 4

**Comment by jrokeach** [comment]
> Acme Inc has developed an application which has to send data which absolutely cannot be lost by the receiver even when the data is sent over a lossy link. What transport layer protocol should Acme Inc use?
> 
> 1. TCP
> 2. UDP 
> 3. DHCP
> 4. ID10T

This one may be able to be used immediately without being multiple choice.

**Comment by hslabbert** [comment]
Which of the following networks belongs to the RFC1918 private ranges?

1. 192.0.2.0/24
2. 8.8.4.0/24
3. 172.27.8.0/23
4. 11.0.0.0/8

**Comment by hslabbert** [comment]
What is the ICMP message type number for ping (echo request)?

**Comment by hslabbert** [comment]
Multiple options we can rotate through:

What is the IP protocol number for:

* TCP
* UDP
* ESP
* AH
* GRE

**Comment by hslabbert** [comment]
Which IPv6 network has been set aside for use in documentation?

**Comment by jrokeach** [comment]
> Acme Inc has developed an application which has to send data which absolutely cannot be lost by the receiver even when the data is sent over a lossy link. What transport layer protocol should Acme Inc use?
> 
> 1. TCP
> 2. UDP
> 3. DHCP
> 4. ID10T

@rahul-sundaresan 
Here's what I'm thinking to go with in the short term, adapting this for a temporarily static question:
> Acme Inc has developed an application which has to send data which absolutely cannot be lost by the receiver even when the data is sent over the Internet. Which common transport layer protocol should the application use?

Of course we still need more if we're building a question pool.

**Comment by jrokeach** [comment]
I'd love something like:
> Ping shows `!.!.!!!!!!.!`. Which network problem exists?
> A) Latency
> B) Slow speeds
> C) Congestion
> D) Packet loss
> E) Jitter
> F) DDoS
But... multiple choice is a problem, at least if they get unlimited tries

**Comment by jrokeach** [comment]
What protocol is used over the network to connect to a router's CLI?

**Comment by jrokeach** [comment]
No longer needed. For now.
