### ISSUE TITLE
Replace static welcome question based on input in #42

### ISSUE THREAD

**Issue by jrokeach** [networking-discord/network-ranger#46]
> Acme Inc has developed an application which has to send data which absolutely cannot be lost by the receiver even when the data is sent over a lossy link. What transport layer protocol should Acme Inc use?
> 
> 1. TCP
> 2. UDP
> 3. DHCP
> 4. ID10T

@rahul-sundaresan 
Here's what I'm thinking to go with in the short term, adapting this for a temporarily static question:
> Acme Inc has developed an application which has to send data which absolutely cannot be lost by the receiver even when the data is sent over the Internet. Which common transport layer protocol should the application use?

Of course we still need more if we're building a question pool.

_Originally posted by @jrokeach in https://github.com/networking-discord/network-ranger/issues/42#issuecomment-647010907_

**Comment by rahul-sundaresan** [comment]
> Here's what I'm thinking to go with in the short term, adapting this for a temporarily static question:
> 
> > Acme Inc has developed an application which has to send data which absolutely cannot be lost by the receiver even when the data is sent over the Internet. Which common transport layer protocol should the application use?
> 
> 
> 
> Of course we still need more if we're building a question pool.
> 
> 
> 
> _Originally posted by @jrokeach in https://github.com/networking-discord/network-ranger/issues/42#issuecomment-647010907_

The question should also have the statement 'write your answer as the well known acronym for protocol '
