### ISSUE TITLE
Implement welcome egging

### ISSUE THREAD

**Issue by jrokeach** [networking-discord/network-ranger#5]
Assign users the `!eggs` role if they answer "eggs".

**Comment by KeatonSK** [comment]
Will this let the person in or will it simply give them the !eggs role and not let them in?

**Comment by jrokeach** [comment]
@KeatonSK it just assigns the eggs role, not the members role. The user needs to get the challenge question correct (with unlimited tries) to get added to the member group

**Comment by KeatonSK** [comment]
Ok, that's what I thought. better to ask. I'll throw that in with my newest version I'm working on mainly to impliment issue #4.
