### ISSUE TITLE
Add a Subnet Calculator

### ISSUE THREAD

**Issue by 1Ludwig** [networking-discord/network-ranger#7]
Would be great to have a subnet calculator for the bot.

**Comment by KeatonSK** [comment]
I'll add that into my build once I get jrokeach's latest build.

**Comment by 1Ludwig** [comment]
I believe the build is up to date. Have you checked it @KeatonSK ?

**Comment by 1Ludwig** [comment]
This could be done fairly simple i believe with a little help from:
https://pypi.org/project/ipcalc/

Something in the style of:
[subnet_calc.txt](https://github.com/networking-discord/network-ranger/files/4448594/subnet_calc.txt)

**Comment by 1Ludwig** [comment]
Have created code in a separate environment that is tested and validated.
Creating a fork so i can merge it with master.

**Comment by 1Ludwig** [comment]
It's been merged to the branch Next.
Awaiting deployment to master.
